LWCQuickStart/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Object for Company Employees</description>
    <label>Employee</label>
    <nameField>
        <label>Employee Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LWCQuickStart/force-app/main/default/objects/Employee__c/fields/Library_ID__c.field-meta.xml
<CustomField>
    <fullName>Library_ID__c</fullName>
    <description>Unique Library Identifier</description>
    <displayFormat>CFS{0000}</displayFormat>
    <externalId>true</externalId>
    <label>Library ID</label>
    <type>AutoNumber</type>
</CustomField>

LWCQuickStart/force-app/main/default/objects/Library_Item__c/Library_Item__c.object-meta.xml
<CustomObject>
    <description>This is the object for Library Items in ConForceSo Corporation</description>
    <label>Library Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Library Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

LWCQuickStart/force-app/main/default/objects/Library_Item__c/fields/BorrowedTo__c.field-meta.xml
<CustomField>
    <fullName>BorrowedTo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <inlineHelpText>Whom is the item borrowed to?</inlineHelpText>
    <label>Borrowed To</label>
    <referenceTo>Employee__c</referenceTo>
    <relationshipLabel>Library Items</relationshipLabel>
    <relationshipName>Library_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

LWCQuickStart/force-app/main/default/objects/Library_Item__c/fields/Item_Number__c.field-meta.xml
<CustomField>
    <fullName>Item_Number__c</fullName>
    <description>Unique number for Library Items</description>
    <displayFormat>{00000}</displayFormat>
    <label>Item Number</label>
    <type>AutoNumber</type>
</CustomField>

LWCQuickStart/force-app/main/default/classes/BorrowingHistoryButton.cls
public class BorrowingHistoryButton {
    @AuraEnabled
    public static List<Employee__c> getBorrowingHistory(String itemNo){
        
        //call searchForID method to get the Id 
        Id libItemId = BorrowingHistoryButton.searchForID(itemNo);
        //query Histories for record matching Id, get history items
        List<Library_Item__History>employeeNames = [SELECT OldValue FROM Library_Item__History
                        WHERE parentId=:libItemId and Field ='BorrowedTo__c'
                                 ];
        List< Employee__c > borrowingHistory = new List<Employee__c> ();
        List<String> IdList = new List<String> ();
        for (Integer i=0; i<employeeNames.size(); i++){
            //filter out items with null values or have Ids displayed
           if(employeeNames[i].OldValue!= null && (string.valueOf(employeeNames[i].OldValue).startsWith('a0'))){
              IdList.add(string.valueOf(employeeNames[i].OldValue));
           }
        }
        for(String empID : IdList){
            Employee__c emp = [SELECT Name, Library_ID__c FROM Employee__c 
                              WHERE Id =: empID];
            borrowingHistory.add(emp);
        }
        
        return borrowingHistory;
    }
    
    @AuraEnabled
    public static Id searchForID(String itemNum){
        List<Id> itemIDList = new List<Id>();
        for(Library_Item__c libItem: [SELECT Id FROM Library_Item__c
                              WHERE Item_Number__c=:itemNum]){
                                  itemIDList.add(libItem.id);
                              }
        
        return itemIDList[0];
    }
}